server:
  port: 8082

spring:
  application:
    name: e-notice
#  data:
#    cassandra:
#      contact-points: 127.0.0.1
#      keyspace-name: ocds
#      port: 9042
#      username: cassandra
#      password: cassandra


cassandra:
  datasource:
    contact-point: 127.0.0.1
    keyspace: ocds
    username: cassandra
    password: cassandra