server:
  port: 8080

spring:
  application:
    name: e-notice

eureka:
  client:
    enabled: false

cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: 6AH7vbrkMWnfK

uri:
  budget: http://public.eprocurement.systems/budget/
  tender: http://public.eprocurement.systems/tender/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"