server:
  port: 8080

spring:
  application:
    name: e-notice

eureka:
  client:
    enabled: false

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

uri:
  budget: http://dev.public.eprocurement.systems/budget/
  tender: http://dev.public.eprocurement.systems/tender/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"