server:
  port: 8080

spring:
  application:
    name: e-notice

eureka:
  client:
    enabled: false

cassandra:
#  contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
  contact-points: 10.0.10.104,10.0.10.105,10.0.10.106
  keyspace-name: ocds
  port: 9042
  username: caclient
  password: brT4Kn27RQs

#cassandra:
#  contact-points: 127.0.0.1
#  keyspace-name: ocds
#  port: 9042
#  username: cassandra
#  password: cassandra

uri:
  budget: http://public.eprocurement.systems/budget/
  tender: http://public.eprocurement.systems/tender/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"